[project]
name = "multi-layer-neural-network"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jinja2>=3.1.5",
    "matplotlib>=3.10.0",
    "pandas>=2.2.3",
    "pip>=24.3.1",
]
